<a href="https://colab.research.google.com/github/skandanyal/Deep_Learning/blob/main/tutorial_0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch

print(torch.__version__)
print(torch.cuda.is_available())

2.8.0+cu126
True


### Information about tensors

1. To get the datatype of a tensor, use `tensor.dtype`
2. To get the shape of a tensor, use `tensor.shape`
3. To get device from a tensor, use `tensor.device`

In [ ]:
# create a tensor

tensor = torch.rand(3,5)
tensor

tensor([[0.1321, 0.2743, 0.9997, 0.4763, 0.8292],
        [0.1569, 0.7626, 0.6836, 0.0980, 0.2187],
        [0.1775, 0.1904, 0.9159, 0.0085, 0.4250]])

In [ ]:
# find out details about the tensor

print(f"Datatype of tensor: {tensor.dtype}")
print(f"Shape of tensor: {tensor.shape}")
print(f"Device of tensor: {tensor.device}")

Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 5])
Device of tensor: cpu


### Tensor ops

* Addition
* Subtraction
* Multiplication - element wise
* Division
* Matrix multiplication

In [ ]:
# Addition

print(tensor + 10)

tensor([[10.1321, 10.2743, 10.9997, 10.4763, 10.8292],
        [10.1569, 10.7626, 10.6836, 10.0980, 10.2187],
        [10.1775, 10.1904, 10.9159, 10.0085, 10.4250]])


In [ ]:
# Multiplication

print(tensor * 10)

tensor([[1.3211, 2.7426, 9.9970, 4.7634, 8.2922],
        [1.5688, 7.6265, 6.8362, 0.9800, 2.1868],
        [1.7751, 1.9040, 9.1586, 0.0851, 4.2501]])


In [ ]:
# Division

print(tensor / 10)

tensor([[0.0132, 0.0274, 0.1000, 0.0476, 0.0829],
        [0.0157, 0.0763, 0.0684, 0.0098, 0.0219],
        [0.0178, 0.0190, 0.0916, 0.0009, 0.0425]])


In [ ]:
print(torch.mul(tensor, 5))
print(torch.multiply(tensor, 5))

tensor([[0.6606, 1.3713, 4.9985, 2.3817, 4.1461],
        [0.7844, 3.8132, 3.4181, 0.4900, 1.0934],
        [0.8875, 0.9520, 4.5793, 0.0425, 2.1251]])
tensor([[0.6606, 1.3713, 4.9985, 2.3817, 4.1461],
        [0.7844, 3.8132, 3.4181, 0.4900, 1.0934],
        [0.8875, 0.9520, 4.5793, 0.0425, 2.1251]])


### Two main ways of matric multiplication

* Element wise multiplication (scalar * matrix)
* Dot product

In [ ]:
# Element wise multiplication

tensor = torch.tensor([1,2,3])
print(tensor.to("cuda") * tensor.to(torch.device("cuda")))
print(tensor.to("cpu"))
print(tensor / tensor)
print(torch.matmul(tensor, tensor))

tensor([1, 4, 9], device='cuda:0')
tensor([1, 2, 3])
tensor([1., 1., 1.])
tensor(14)


In [ ]:
# shapes for matric multiplication

tensor_A = torch.tensor(
    [[1,2],
     [3,4],
     [5,6]]
)

# torch.mm(tensor_A, tensor_A)

In [ ]:
tensor_B = torch.tensor([
    [1,2,4],
    [5,6,8]
])

torch.mm(tensor_A, tensor_B)

tensor([[11, 14, 20],
        [23, 30, 44],
        [35, 46, 68]])

In [ ]:
torch.matmul(tensor_A, tensor_A.T)

tensor([[ 5, 11, 17],
        [11, 25, 39],
        [17, 39, 61]])

In [ ]:
print(f"1. {tensor_A.argmax()}")
print(f"2. {tensor_A.argmax().item()}")

1. 5
2. 5


## Reshaping, stacking, squeexing and unsqueezing tensors

* Reshaping - reshapes in input tensor to a defined shape
* View - shows the same tensor, but from a different perspective
* Stacking - combining multiple tensors on top of each other (vertical stack) or side by side (horizontle stack)
* Squeeze - removes all `1` dimensions from a tensor
* Unsqueeze - adds a `1` dimension to a target tensor
* permute - returns a view of the input with dimensions permuted (swapped) in a certain way

In [ ]:
# create a tensor

import torch

x = torch.arange(1,10)
print(x, x.shape)

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]) torch.Size([9])


In [ ]:
# add an extra dimension

x_reshaped = x.reshape(3,3)
print(x_reshaped, x_reshaped.shape)

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]) torch.Size([3, 3])


In [ ]:
# change the view

x_reshaped.view(9, 1)

tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8],
        [9]])

In [ ]:
# stack tensors on top of each other

x_stacked = torch.stack([x,x,x,x], dim=1)
x_stacked

tensor([[1, 1, 1, 1],
        [2, 2, 2, 2],
        [3, 3, 3, 3],
        [4, 4, 4, 4],
        [5, 5, 5, 5],
        [6, 6, 6, 6],
        [7, 7, 7, 7],
        [8, 8, 8, 8],
        [9, 9, 9, 9]])

In [ ]:
# torch.squeeze() removes all single dimensions from the target tensor

x, x.shape

(tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]), torch.Size([9]))

In [ ]:
x.squeeze(), x.squeeze().shape

# mm hmm.. we did not get the [9,1] by default, hence we are not able to see the function in action

(tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]), torch.Size([9]))

In [ ]:
# torch.unsqueeze() adds a single dimension to a target tensor at a target tensor at a specidic dimension

x_squeezed = x_reshaped.squeeze()
print(f"Previous target: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

# add an extra dimension with unsqueeze

x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous target: tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
Previous shape: torch.Size([3, 3])

New tensor: tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])
New shape: torch.Size([1, 3, 3])


In [ ]:
# torch.permute() - rearranges the dimensiond od a target tensor in the specified way

x_og = torch.rand(size=(224,224,3)) # height, width and colour_channels

# permute the og tensor to rearrange the axes (or dimensions) order

x_permuted = x_og.permute(2, 0, 1) # shifts the axis 0->1, 1->2, 2->0

print(f"Previous shape: {x_og.shape}")
print(f"New shape: {x_permuted.shape}") # colour_channels, height, width

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


In [ ]:
# since the permuted tensor is a view of the original tensor, let us try by changing the value of a particular cell

x_og[0,0,0] = 11111

x_og[0,0,0], x_permuted[0,0,0]

(tensor(11111.), tensor(11111.))

# Indexing (selecting data from tensors)

Indexing with PyTorch is similar to indexing with NumPy

In [ ]:
# Create a tensor

import torch

x = torch.arange(1,10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [ ]:
# Let us index on our new tensor

x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
# indexing on the middle bracket

x[0][2]

tensor([7, 8, 9])

In [ ]:
# indexing on the third dimension

x[0][1][2]

tensor(6)

In [ ]:
x[:, :, 2]

tensor([[3, 6, 9]])

## Reproducibility (trying to take out randomness out of randomness)

How neural networks learn:    
`start with random numbers` -> `tensor operations` -> `update random numbers to make them better represent the data` -> repeat



In [ ]:
import torch

torch.rand((3,3))

tensor([[0.1255, 0.4092, 0.6088],
        [0.6935, 0.6083, 0.4822],
        [0.4151, 0.8732, 0.3371]])

To reduce randomness in PyTorch, use the concept of `random seed`.    
It essentially flavours the randomness.

In [ ]:
# create two random tensors

random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)

print(random_tensor_A == random_tensor_B)

tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [ ]:
# Creating random but reproducible tensors

RANDOM_SEED = 5

torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3,4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3,4)

random_tensor_C == random_tensor_D

tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

## Running tensors on GPU

### Getting a GPU -


1.   Use Colab/Kaggle
2.   Get a discrete graphics card for yourself
3.   Cloud computing pe rent pe lo

In [ ]:
!nvidia-smi

Wed Aug 20 12:02:56 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   49C    P8             10W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----